# Generated by Django 3.0.2 on 2020-01-30 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMarket',
            fields=[
                ('market_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('market_name', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('time_zone', models.IntegerField()),
                ('open_time', models.CharField(max_length=5)),
                ('close_time', models.CharField(max_length=5)),
                ('lunch_break', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'stock_market_lookup_table',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_symbol', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=10)),
                ('info_link', models.CharField(max_length=50)),
                ('stock_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicApp.StockMarket')),
            ],
            options={
                'db_table': 'stock_lookup_table',
            },
        ),
    ]
