# Generated by Django 3.0.2 on 2020-02-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='info_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='market_name',
            field=models.CharField(max_length=20),
        ),
    ]
