# Generated by Django 3.0.2 on 2020-02-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicApp', '0002_auto_20200201_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarket',
            name='market_name',
            field=models.CharField(max_length=50),
        ),
    ]
