# Generated by Django 3.0.2 on 2020-02-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicApp', '0003_auto_20200209_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarket',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='close_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='lunch_break',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='market_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockmarket',
            name='open_time',
            field=models.CharField(max_length=50),
        ),
    ]
