# Generated by Django 3.0.2 on 2020-02-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicApp', '0004_auto_20200209_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarket',
            name='time_zone',
            field=models.FloatField(),
        ),
    ]
