# Generated by Django 3.0.2 on 2020-02-13 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicApp', '0006_auto_20200209_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupTablesUpdateStatus',
            fields=[
                ('table_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('last_update', models.TimeField(auto_now=True)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockDataLastUpdate',
            fields=[
                ('stock_market', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BasicApp.Stock')),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
