# Generated by Django 3.0.2 on 2020-02-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicApp', '0007_lookuptablesupdatestatus_stockdatalastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='info_link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_symbol',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
