# Generated by Django 3.0.2 on 2020-02-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicApp', '0010_auto_20200215_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stock_symbol', models.CharField(max_length=20)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'db_table': 'OHLCV_table',
            },
        ),
        migrations.DeleteModel(
            name='LookupTablesUpdateStatus',
        ),
    ]
