# Generated by Django 3.0.2 on 2020-03-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicApp', '0011_auto_20200215_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieCrumbPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.BinaryField()),
                ('crumb', models.CharField(max_length=20)),
                ('saved_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'CookieCrumbPair_table',
            },
        ),
        migrations.AlterModelTable(
            name='stockdatalastupdate',
            table='StockDataLastUpdate_table',
        ),
    ]
